name: checkt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  font_awesome_flutter: ^10.7.0
  curved_navigation_bar: ^1.0.3
  slide_to_act: ^2.0.2
  cloud_firestore: ^4.17.3
  shared_preferences: ^2.2.3
  intl: ^0.18.1
  animate_do: ^3.3.4
  month_year_picker: ^0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
